version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'zen-chef-mongo'
    restart: always
    environment:
      MONGO_INITDB_DATABASE: zenchef
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./database:/data/db
    ports:
      - '27017-27019:27017-27019'
